### PR TITLE
Log timediff (galactic)

### PR DESCRIPTION
**Pull request by ihkao**

### CODE REVIEW

**Comment by JWhitleyWork** [comment]
Would you be OK just putting the function definition in the header file? This simplifies things a bit.

**Comment by ihkao** [comment]
> ` [a9ac982](/upowerrobotics/rmw_cyclonedds/pull/1/commits/a9ac9828daee1b9f9b2f97c4bcb48e16b974fb02)`

Fix in [a9ac982](https://github.com/upowerrobotics/rmw_cyclonedds/pull/1/commits/a9ac9828daee1b9f9b2f97c4bcb48e16b974fb02)

**Comment by ihkao** [comment]
> Would you be OK just putting the function definition in the header file? This simplifies things a bit.

Fix in [a9ac982](https://github.com/upowerrobotics/rmw_cyclonedds/pull/1/commits/a9ac9828daee1b9f9b2f97c4bcb48e16b974fb02)

**Review by JWhitleyWork — APPROVED** [review]
LGTM

**Pull request merged**
